#### First lesson: Tensor Math and Comparison Operations: 
-  Tensor indexing
-  Tensor Reshaping

In [6]:
import torch
import numpy as np

1. what is a tensor and how to create a tensor?
- Tensor is multi-dimentional matrix containing elements of a single data type

In [2]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

2. Can we also set the type while initializing? Yes
3. How?

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor =  torch.tensor([[1,2,3],[4,5,6]],device=device)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [3]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape) # 2 rows and 3 columns
print(my_tensor.requires_grad)

torch.int64
cuda:0
torch.Size([2, 3])
False


In [5]:
# create an zero 3*3 tensor
x = torch.empty(size = (3,3))
print(x)

y = torch.zeros(3,3)
print(y)

# initializing random tensors
f = torch.rand(3,3, dtype=torch.float16)
print(f)

# initializing ones tensor
z = torch.ones(3,3)
print(z)

# initializing identical tensor
i = torch.eye(5,5, dtype=torch.int16)
print(i)

# remember by default the data type is float32 in tensors
print(x.dtype)
print(y.dtype)
print(f.dtype)
print(z.dtype)
print(i.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1035, 0.3877, 0.7842],
        [0.9629, 0.5405, 0.9829],
        [0.4155, 0.2939, 0.7920]], dtype=torch.float16)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)
torch.float32
torch.float32
torch.float16
torch.float32
torch.int16
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)


In [4]:
x = torch.arange(start=0, end=5, step=1) # this is kind range, which we apply in loop 
print(x)

tensor([0, 1, 2, 3, 4])


In [5]:
x = torch.linspace(start=0.1,end=1,steps=10) # this fuction also work as loop
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


n.b: remember that torch is core library of pytorch framework

In [7]:
x = torch.empty(1,5).normal_(mean=0,std=1) # initializing normal distribution, here std is standard deviation.
print(x)

tensor([[-0.6199,  0.4872, -0.0413,  1.3820, -1.1765]])


In [9]:
x = torch.empty(1,5).uniform_(0,1) # initializing uniform distribution
print(x)

tensor([[0.5779, 0.8102, 0.9275, 0.1023, 0.7566]])


In [10]:
x = torch.diag(torch.ones(3)) # another way to initialize identity matrix
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### How to initialize and convert tensors to another types such as int, float, double

In [5]:
tensor = torch.arange(4)

print(tensor)
print(tensor.bool()) # convert to boolen(True/False)
print(tensor.short()) # int16
print(tensor.long()) # int64(Important)
print(tensor.half()) # float16
print(tensor.float()) # float32 (Important)
print(tensor.double()) #float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [9]:
# Array to tensor conversion
np.array = np.zeros((5,5))
tensor = torch.from_numpy(np.array)
print(tensor)
np_array_back = tensor.numpy() # tensors to numpy array conversion
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
