#### First lesson: Tensor Math and Comparison Operations: 
-  Tensor indexing
-  Tensor Reshaping

In [1]:
import torch
import numpy as np

1. what is a tensor and how to create a tensor?
- Tensor is multi-dimentional matrix containing elements of a single data type

In [2]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
my_tensor.size() # 2X3 tensor

torch.Size([2, 3])

2. Can we also set the type while initializing? Yes
3. How?

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor =  torch.tensor([[1,2,3],[4,5,6]],device=device)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [3]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape) # 2 rows and 3 columns
print(my_tensor.requires_grad)

torch.int64
cuda:0
torch.Size([2, 3])
False


In [5]:
# create an zero 3*3 tensor
x = torch.empty(size = (3,3))
print(x)

y = torch.zeros(3,3)
print(y)

# initializing random tensors
f = torch.rand(3,3, dtype=torch.float16)
print(f)

# initializing ones tensor
z = torch.ones(3,3)
print(z)

# initializing identical tensor
i = torch.eye(5,5, dtype=torch.int16)
print(i)

# remember by default the data type is float32 in tensors
print(x.dtype)
print(y.dtype)
print(f.dtype)
print(z.dtype)
print(i.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1035, 0.3877, 0.7842],
        [0.9629, 0.5405, 0.9829],
        [0.4155, 0.2939, 0.7920]], dtype=torch.float16)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)
torch.float32
torch.float32
torch.float16
torch.float32
torch.int16
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)


In [4]:
x = torch.arange(start=0, end=5, step=1) # this is kind range, which we apply in loop 
print(x)

tensor([0, 1, 2, 3, 4])


In [5]:
x = torch.linspace(start=0.1,end=1,steps=10) # this fuction also work as loop
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


n.b: remember that torch is core library of pytorch framework

In [7]:
x = torch.empty(1,5).normal_(mean=0,std=1) # initializing normal distribution, here std is standard deviation.
print(x)

tensor([[-0.6199,  0.4872, -0.0413,  1.3820, -1.1765]])


In [9]:
x = torch.empty(1,5).uniform_(0,1) # initializing uniform distribution
print(x)

tensor([[0.5779, 0.8102, 0.9275, 0.1023, 0.7566]])


In [10]:
x = torch.diag(torch.ones(3)) # another way to initialize identity matrix
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### How to initialize and convert tensors to another types such as int, float, double

In [5]:
tensor = torch.arange(4)

print(tensor)
print(tensor.bool()) # convert to boolen(True/False)
print(tensor.short()) # int16
print(tensor.long()) # int64(Important)
print(tensor.half()) # float16
print(tensor.float()) # float32 (Important)
print(tensor.double()) #float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [9]:
# Array to tensor conversion
np.array = np.zeros((5,5))
tensor = torch.from_numpy(np.array)
print(tensor)
np_array_back = tensor.numpy() # tensors to numpy array conversion
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Tensor Math and Comparison Operation

In [9]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
add = x + y
print(f"Addition: \n{add}\n")

# we can do this in two other ways
add = torch.empty(3)
torch.add(x,y,out=add) 
print(f"Addition: \n{add}\n") # this actually took float

add = torch.add(x,y)
print(f"Addition: \n{add}\n")

# subtraction
substract = x-y
print(f"Substraction: \n{substract}\n")

# Element wise multiplication
multiply = x*y
print(f"Multiplication: \n{multiply}\n")

multiply = torch.mul(x,y)
print(f"Multiplication: \n{multiply}\n")

# Division
div = torch.true_divide(x,y) # if x and y are of equal shape then this function will do the element wise division.
print(f"Division: \n{div}\n")

div = x/y
print(f"Division: \n{div}\n")

# Inline operation: It will mutate the tensors in place so it does not create a copy. This is more computationally efficient
t = torch.zeros(3)
print(f"Inline addition: \n{t.add_(x)}\n")

# Exponentiation
z = x.pow(2) # this is going to be element wise power of 2
print(f"Exponent operation: \n{z}\n")

# same operation can be done using the following way as well
z = y**2
print(f"Exponent operation: \n{z}\n")

# Simple Comparison
z = x>=2 # element wise comparison
print(f"Comparison operation: \n{z}\n")

# Matrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2) # 2x3 matrix
print(f"Matrix Multiplication: \n{x3}\n")

# Matrix exponentiation
matrix_exp = torch.rand(5,5)
print(f"Matrix Exponentiation: \n{matrix_exp.matrix_power(3)}\n")

# dot product
print(f"Dot Product: \n{torch.dot(x,y)}\n")

# Batch Matrix Multiplication
batch = 32
n = 18
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1,tensor2) # here the resulting sape is going to be batch X n X p
print(f"Batch Matrix Multiplication: \n{out_bmm}\n")

Addition: 
tensor([10, 10, 10])

Addition: 
tensor([10., 10., 10.])

Addition: 
tensor([10, 10, 10])

Substraction: 
tensor([-8, -6, -4])

Multiplication: 
tensor([ 9, 16, 21])

Multiplication: 
tensor([ 9, 16, 21])

Division: 
tensor([0.1111, 0.2500, 0.4286])

Division: 
tensor([0.1111, 0.2500, 0.4286])

Inline addition: 
tensor([1., 2., 3.])

Exponent operation: 
tensor([1, 4, 9])

Exponent operation: 
tensor([81, 64, 49])

Comparison operation: 
tensor([False,  True,  True])

Matrix Multiplication: 
tensor([[1.0745, 0.8961, 1.1154],
        [1.4188, 1.4805, 1.7147]])

Matrix Exponentiation: 
tensor([[6.6764, 4.7321, 3.3850, 5.4056, 8.2055],
        [7.1324, 4.8272, 3.5300, 5.4811, 8.4673],
        [4.1117, 2.8904, 2.0978, 3.3235, 5.0634],
        [6.7270, 4.6581, 3.3548, 5.1807, 8.0578],
        [4.6045, 3.0566, 2.2322, 3.3903, 5.3406]])

Dot Product: 
46

Batch Matrix Multiplication: 
tensor([[[5.6502, 3.2130, 3.3010,  ..., 5.8226, 4.5997, 4.5176],
         [5.5289, 3.2088, 3.5162,

In [4]:
# Example of broadcasting which refers as the dimention automatically expands

x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1-x2 
print(z)
''' In order to do mathematical operation in matrix x1's coulmn and x2's row should be matched, 
but pytorch can do this operation by broadcasting. 
Also as x2 has only one row it is also consider as a vector. 
So, the row of x2 will expand in order to match the row of x1. '''

z = x1**x2
print(z)

tensor([[-0.8348, -0.0798,  0.0364, -0.5262,  0.6617],
        [-0.5570,  0.2229, -0.0034,  0.0691,  0.6039],
        [-0.3877,  0.0316, -0.0850, -0.4416,  0.3508],
        [ 0.0348, -0.1991, -0.4018, -0.0495,  0.6090],
        [-0.0684,  0.1269,  0.1443,  0.0906,  0.3377]])
tensor([[0.0405, 0.6325, 0.8313, 0.3258, 0.9868],
        [0.3574, 0.8234, 0.7995, 0.8614, 0.9688],
        [0.5239, 0.7136, 0.7330, 0.4142, 0.8789],
        [0.9079, 0.5180, 0.4500, 0.7661, 0.9704],
        [0.8171, 0.7717, 0.9153, 0.8783, 0.8737]])


#### Some other useful Tensor operations

In [31]:
sum_x = torch.sum(x, dim=0) # summation of x tensor
print(sum_x)

values, indices = torch.max(x,dim=0) # dim = 0 means vector
print(values, indices)
values, indices = torch.min(x,dim=0) 
print(values, indices)

abs_x = torch.abs(x) # absolute
print(abs_x)
abs_x = x.abs()
print(abs_x)

z = torch.argmax(x, dim=0) # maxium argument/index
print(z)
z = x.argmax(dim=0)
print(z)

z = torch.argmin(x, dim=0) # minium argument/index
print(z)
z = x.argmin(dim=0)
print(z)

mean_x = torch.mean(x.float(),dim=0) # need to convert the type
print(mean_x)

z = torch.eq(x,y)
print(z)

sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y, indices)

z = torch.clamp(x, min=5) # it means if the numbers in tensors are less than 5 than clamp will set them to 5 according the minimum number that are given
print(z)

x_ = torch.tensor([1,0,1,1], dtype=torch.bool)
z = torch.any(x_)
print(z)
z = torch.all(x_)
print(z)

tensor(6)
tensor(3) tensor(2)
tensor(1) tensor(0)
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor(2)
tensor(2)
tensor(0)
tensor(0)
tensor(2.)
tensor([False, False, False])
tensor([7, 8, 9]) tensor([2, 1, 0])
tensor([5, 5, 5])
tensor(True)
tensor(False)


#### Tensor Indexing

In [14]:
batch_size = 10
features = 15

x = torch.rand(batch_size, features)
print(x)
print(x[0]) # it will print all the 15 features of 0th index
print(x[:,0]) # first feature in all of our example
print(x[2,0:10]) # take 10 features from the 3rd index
# lets see the shape in bothe the cases
print(x[0].shape)
print(x[:,0].shape)
print(x[2,0:10].shape)

tensor([[0.5393, 0.6869, 0.8288, 0.6741, 0.1927, 0.8545, 0.0163, 0.0348, 0.6801,
         0.6259, 0.3022, 0.6894, 0.7974, 0.2682, 0.1275],
        [0.8488, 0.3128, 0.9031, 0.7936, 0.1774, 0.8228, 0.2481, 0.4913, 0.4897,
         0.9311, 0.3996, 0.0611, 0.9340, 0.1657, 0.5322],
        [0.2726, 0.1205, 0.4681, 0.2117, 0.6555, 0.6519, 0.2258, 0.6417, 0.1670,
         0.6236, 0.1237, 0.9501, 0.1984, 0.6873, 0.3710],
        [0.5691, 0.5202, 0.4607, 0.0246, 0.9611, 0.8418, 0.6211, 0.5605, 0.7948,
         0.2943, 0.4455, 0.4311, 0.3983, 0.9736, 0.2689],
        [0.8611, 0.2444, 0.0199, 0.5896, 0.1082, 0.9319, 0.2765, 0.5471, 0.0208,
         0.7687, 0.9707, 0.4730, 0.8696, 0.1027, 0.0259],
        [0.7018, 0.7830, 0.6700, 0.3161, 0.8329, 0.4719, 0.0097, 0.9065, 0.2836,
         0.0111, 0.5266, 0.8768, 0.4583, 0.5706, 0.1775],
        [0.2941, 0.3834, 0.0794, 0.6196, 0.5731, 0.7413, 0.6355, 0.6442, 0.7356,
         0.0134, 0.0511, 0.9553, 0.5135, 0.9518, 0.3686],
        [0.9148, 0.3531, 0.

In [32]:
# fancy indexing
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

x = torch.rand(3,5) 
''' The torch.rand() function generates a tensor filled with random values sampled from a uniform distribution in the range [0, 1). 
This means that all values will be random floats between 0 (inclusive) and 1 (exclusive).'''
rows = torch.tensor([1,0]) # this means row 1 and 0 is taken
cols = torch.tensor([4,0]) # column 4 and 0 taken
print(x[rows,cols]) # x[1,4],x[0,0]
print(x[rows,cols].shape)

x = torch.arange(10)
print(x[(x<2)|(x>8)])
print(x[(x<2)&(x>8)])
print(x[x.remainder(2)==0]) # even index

print(torch.where(x>5,x,x*2)) # conditional indexing
print(torch.tensor([0,0,1,1,2,3,4]).unique()) 
print(x.ndimension()) # number of dimensions
print(x.numel()) # number of elements in x

tensor([2, 5, 8])
tensor([0.9693, 0.6922])
torch.Size([2])
tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


#### Tensor Reshaping 

In [9]:
x = torch.arange(9)
print(x)
x_3x3 = x.view(3,3)
print(x_3x3)

x_3x3 = x.reshape(3,3)
#print(x_3x3)

''' for view contigous memroy allocation is needed for reshape contigous memory is not needed, so it is better to use reshape '''

y = x_3x3.t() # transpose
print(y) 
print(y.reshape(9))  

# concatenate
x1 = torch.rand(2,5)
x2 = torch.rand(2,5)

print(torch.cat((x1,x2),dim=0).shape) # row wise concatenate
print(torch.cat((x1,x2),dim=1).shape) # column wise concatenate


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])


In [15]:
z = x1.view(-1) # flattening the x1 tensor
print(z.shape)

# flattening again with a bit more complicacy
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch,-1)
print(z.shape)

# switching the axis
z = x.permute(0,2,1)
print(z.shape)

x = torch.arange(10)
print(x.unsqueeze(0).shape) # 1x10 vector
print(x.unsqueeze(1).shape) # 10x1 vector

x = torch.arange(10).unsqueeze(0).unsqueeze(1) #1x1x10
print(x.shape)

z = x.squeeze(1)
print(z.shape)

torch.Size([10])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
torch.Size([1, 10])
