#### First lesson: Tensor Math and Comparison Operations: 
-  Tensor indexing
-  Tensor Reshaping

In [1]:
import torch
import numpy as np

1. what is a tensor and how to create a tensor?
- Tensor is multi-dimentional matrix containing elements of a single data type

In [2]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

2. Can we also set the type while initializing? Yes
3. How?

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor =  torch.tensor([[1,2,3],[4,5,6]],device=device)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [3]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape) # 2 rows and 3 columns
print(my_tensor.requires_grad)

torch.int64
cuda:0
torch.Size([2, 3])
False


In [5]:
# create an zero 3*3 tensor
x = torch.empty(size = (3,3))
print(x)

y = torch.zeros(3,3)
print(y)

# initializing random tensors
f = torch.rand(3,3, dtype=torch.float16)
print(f)

# initializing ones tensor
z = torch.ones(3,3)
print(z)

# initializing identical tensor
i = torch.eye(5,5, dtype=torch.int16)
print(i)

# remember by default the data type is float32 in tensors
print(x.dtype)
print(y.dtype)
print(f.dtype)
print(z.dtype)
print(i.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1035, 0.3877, 0.7842],
        [0.9629, 0.5405, 0.9829],
        [0.4155, 0.2939, 0.7920]], dtype=torch.float16)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)
torch.float32
torch.float32
torch.float16
torch.float32
torch.int16
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)


In [4]:
x = torch.arange(start=0, end=5, step=1) # this is kind range, which we apply in loop 
print(x)

tensor([0, 1, 2, 3, 4])


In [5]:
x = torch.linspace(start=0.1,end=1,steps=10) # this fuction also work as loop
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


n.b: remember that torch is core library of pytorch framework

In [7]:
x = torch.empty(1,5).normal_(mean=0,std=1) # initializing normal distribution, here std is standard deviation.
print(x)

tensor([[-0.6199,  0.4872, -0.0413,  1.3820, -1.1765]])


In [9]:
x = torch.empty(1,5).uniform_(0,1) # initializing uniform distribution
print(x)

tensor([[0.5779, 0.8102, 0.9275, 0.1023, 0.7566]])


In [10]:
x = torch.diag(torch.ones(3)) # another way to initialize identity matrix
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### How to initialize and convert tensors to another types such as int, float, double

In [5]:
tensor = torch.arange(4)

print(tensor)
print(tensor.bool()) # convert to boolen(True/False)
print(tensor.short()) # int16
print(tensor.long()) # int64(Important)
print(tensor.half()) # float16
print(tensor.float()) # float32 (Important)
print(tensor.double()) #float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [9]:
# Array to tensor conversion
np.array = np.zeros((5,5))
tensor = torch.from_numpy(np.array)
print(tensor)
np_array_back = tensor.numpy() # tensors to numpy array conversion
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Tensor Math and Comparison Operation

In [5]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
add = x + y
print(add)

# we can do this in two other ways
add = torch.empty(3)
torch.add(x,y,out=add) 
print(add) # this actually took float

add = torch.add(x,y)
print(add)

# subtraction
substract = x-y
print(substract)

# Division
div = torch.true_divide(x,y) # if x and y are of equal shape then this function will do the element wise division.
print(div)

# Inline operation: It will mutate the tensors in place so it does not create a copy. This is more computationally efficient
t = torch.zeros(3)
t.add_(x)

# Exponentiation
z = x.pow(2) # this is going to be element wise power of 2
print(z)

# same operation can be done using the following way as well
z = y**2
print(z)

# Simple Comparison
z = x>=2 # element wise comparison
print(z)

# Matrix Multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2) # 2x3 matrix
print(x3)

# Matrix exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

# Element wise multiplication
z = x*y
print(z)

# dot product
print(torch.dot(x,y))

# Batch Matrix Multiplication
batch = 32
n = 18
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1,tensor2) # here the resulting sape is going to be batch x n x p
print(out_bmm)


tensor([10, 10, 10])
tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([1, 4, 9])
tensor([81, 64, 49])
tensor([False,  True,  True])
tensor([[1.0353, 1.2403, 1.3911],
        [1.1310, 1.2695, 1.5597]])
tensor([[4.2205, 4.6985, 6.3367, 4.6345, 5.9974],
        [5.0501, 5.7884, 7.7029, 5.6104, 7.2472],
        [5.0635, 5.5903, 7.6489, 5.5811, 7.3397],
        [2.6336, 2.8599, 3.9262, 2.9352, 3.7883],
        [3.3614, 3.8283, 5.1608, 3.7158, 4.9031]])
tensor([ 9, 16, 21])
tensor(46)
tensor([[[4.6665, 5.8531, 5.6283,  ..., 6.0059, 4.7276, 6.0091],
         [6.2954, 6.9808, 5.9412,  ..., 6.9019, 5.8387, 6.7398],
         [4.9542, 5.6323, 5.2925,  ..., 6.1177, 4.9166, 6.3650],
         ...,
         [3.4880, 4.9879, 4.1245,  ..., 4.8057, 3.1981, 4.7789],
         [4.2582, 5.5967, 4.5030,  ..., 5.0436, 4.2113, 5.6136],
         [6.1049, 5.5373, 5.3629,  ..., 5.8419, 5.0935, 5.7556]],

        [[4.2103, 4.6701, 4.4194,  ..., 4.9626, 5.061

In [4]:
# Example of broadcasting which refers as the dimention automatically expands

x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1-x2 
print(z)
''' In order to do mathematical operation in matrix x1's coulmn and x2's row should be matched, 
but pytorch can do this operation by broadcasting. 
Also as x2 has only one row it is also consider as a vector. 
So, the row of x2 will expand in order to match the row of x1. '''

z = x1**x2
print(z)

tensor([[-0.8348, -0.0798,  0.0364, -0.5262,  0.6617],
        [-0.5570,  0.2229, -0.0034,  0.0691,  0.6039],
        [-0.3877,  0.0316, -0.0850, -0.4416,  0.3508],
        [ 0.0348, -0.1991, -0.4018, -0.0495,  0.6090],
        [-0.0684,  0.1269,  0.1443,  0.0906,  0.3377]])
tensor([[0.0405, 0.6325, 0.8313, 0.3258, 0.9868],
        [0.3574, 0.8234, 0.7995, 0.8614, 0.9688],
        [0.5239, 0.7136, 0.7330, 0.4142, 0.8789],
        [0.9079, 0.5180, 0.4500, 0.7661, 0.9704],
        [0.8171, 0.7717, 0.9153, 0.8783, 0.8737]])


#### Some other useful Tensor operations