#### First lesson: Tensor Math and Comparison Operations: 
-  Tensor indexing
-  Tensor Reshaping

In [2]:
import torch
import numpy as np

1. what is a tensor and how to create a tensor?
- Tensor is multi-dimentional matrix containing elements of a single data type

In [2]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

2. Can we also set the type while initializing? Yes
3. How?

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor =  torch.tensor([[1,2,3],[4,5,6]],device=device)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [3]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape) # 2 rows and 3 columns
print(my_tensor.requires_grad)

torch.int64
cuda:0
torch.Size([2, 3])
False


In [5]:
# create an zero 3*3 tensor
x = torch.empty(size = (3,3))
print(x)

y = torch.zeros(3,3)
print(y)

# initializing random tensors
f = torch.rand(3,3, dtype=torch.float16)
print(f)

# initializing ones tensor
z = torch.ones(3,3)
print(z)

# initializing identical tensor
i = torch.eye(5,5, dtype=torch.int16)
print(i)

# remember by default the data type is float32 in tensors
print(x.dtype)
print(y.dtype)
print(f.dtype)
print(z.dtype)
print(i.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1035, 0.3877, 0.7842],
        [0.9629, 0.5405, 0.9829],
        [0.4155, 0.2939, 0.7920]], dtype=torch.float16)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)
torch.float32
torch.float32
torch.float16
torch.float32
torch.int16
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int16)


In [4]:
x = torch.arange(start=0, end=5, step=1) # this is kind range, which we apply in loop 
print(x)

tensor([0, 1, 2, 3, 4])


In [5]:
x = torch.linspace(start=0.1,end=1,steps=10) # this fuction also work as loop
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


n.b: remember that torch is core library of pytorch framework

In [7]:
x = torch.empty(1,5).normal_(mean=0,std=1) # initializing normal distribution, here std is standard deviation.
print(x)

tensor([[-0.6199,  0.4872, -0.0413,  1.3820, -1.1765]])


In [9]:
x = torch.empty(1,5).uniform_(0,1) # initializing uniform distribution
print(x)

tensor([[0.5779, 0.8102, 0.9275, 0.1023, 0.7566]])


In [10]:
x = torch.diag(torch.ones(3)) # another way to initialize identity matrix
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### How to initialize and convert tensors to another types such as int, float, double

In [5]:
tensor = torch.arange(4)

print(tensor)
print(tensor.bool()) # convert to boolen(True/False)
print(tensor.short()) # int16
print(tensor.long()) # int64(Important)
print(tensor.half()) # float16
print(tensor.float()) # float32 (Important)
print(tensor.double()) #float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [9]:
# Array to tensor conversion
np.array = np.zeros((5,5))
tensor = torch.from_numpy(np.array)
print(tensor)
np_array_back = tensor.numpy() # tensors to numpy array conversion
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Tensor Math and Comparison Operation

In [27]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
add = x + y
print(add)

# we can do this in two other ways
add = torch.empty(3)
torch.add(x,y,out=add) 
print(add) # this actually took float

add = torch.add(x,y)
print(add)

# subtraction
substract = x-y
print(substract)

# Division
div = torch.true_divide(x,y) # if x and y are of equal shape then this function will do the element wise division.
print(div)

# Inline operation: It will mutate the tensors in place so it does not create a copy. This is more computationally efficient
t = torch.zeros(3)
t.add_(x)

# Exponentiation
z = x.pow(2) # this is going to be element wise power of 2
print(z)

# same operation can be done using the following way as well
z = y**2
print(z)

# Simple Comparison
z = x>=2 # element wise comparison
print(z)

# Matrix Multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2) # 2x3 matrix
print(x3)

# Matrix exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

# Element wise multiplication
z = x*y
print(z)

# dot product
print(torch.dot(x,y))

# Batch Matrix Multiplication
batch = 32
n = 18
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1,tensor2) # here the resulting sape is going to be batch x n x p
print(out_bmm)


tensor([10, 10, 10])
tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([1, 4, 9])
tensor([81, 64, 49])
tensor([False,  True,  True])
tensor([[1.0164, 1.4687, 1.1126],
        [1.0985, 1.3218, 0.8300]])
tensor([[1.5308, 3.2597, 2.6153, 2.8035, 1.7482],
        [2.0056, 3.8015, 3.1641, 3.3650, 2.0977],
        [1.3042, 2.4204, 1.9304, 2.0638, 1.2986],
        [1.3060, 2.6803, 2.0780, 2.1835, 1.4246],
        [1.3303, 2.9055, 2.1439, 2.5185, 1.4224]])
tensor([ 9, 16, 21])
tensor(46)
tensor([[[5.4113, 5.3606, 5.8773,  ..., 5.7394, 4.7015, 5.4841],
         [5.5988, 5.0432, 5.9996,  ..., 4.9456, 3.8071, 5.0429],
         [5.6024, 4.4092, 5.6877,  ..., 5.0827, 3.0945, 4.2451],
         ...,
         [5.6531, 5.2391, 5.8490,  ..., 5.4551, 3.9255, 5.2075],
         [5.5591, 4.8665, 5.3039,  ..., 4.9394, 3.9644, 5.0110],
         [4.9859, 5.5701, 6.3920,  ..., 5.5455, 4.3300, 5.6540]],

        [[4.3929, 6.2515, 4.5610,  ..., 6.0453, 4.134